test:
	npx playwright test

headed:
	npx playwright test --headed

ui:
	npx playwright test --ui

report:
	npx playwright show-report

update:
	npm install -D @playwright/test@latest && npx playwright install --with-deps
