version: "3.8"

services:
  flask:
    build: .
    container_name: flask_app
    restart: always
    # environment:
    #   - API_KEY=${API_KEY}
    env_file:
      - ./envs/runtime.env
    ports:
      - "80:80"
